name: build

on:
    push:
        tags:
            - "v*"

permissions:
    contents: write

jobs:
    compile:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4
            - uses: denoland/setup-deno@v1
              with:
                  deno-version-file: .tool-versions
            - run: deno task compile
            - run: Compress-Archive -Path "vscode-pretty-styles\\*" -DestinationPath "vscode-pretty-styles.zip"
            - uses: softprops/action-gh-release@v2
              with:
                  files: vscode-pretty-styles.zip
